---
- name: Jenkins server starting and installing plugins and making connection with instance
  hosts: my_ec2
  become: true
  vars:
    public_ip: "{{ ansible_host }}"
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Run Jenkins container with volume and port mapping
      docker_container:
        name: jenkins
        image: jenkins/jenkins:lts
        state: started
        ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
          - "/var/www/html:/tmp/html"
        user: root
        
    - name: Wait for Jenkins to start
      wait_for:
        port: 8080
        delay: 120

    - name: Download Jenkins CLI
      get_url:
        url: http://{{ public_ip }}:8080/jnlpJars/jenkins-cli.jar
        dest: /tmp/jenkins-cli.jar

    - name: Retrieve the initial admin password
      command: docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword
      register: admin_password

    - name: Install Git plugin
      command: >
        java -jar /tmp/jenkins-cli.jar -s http://{{ public_ip }}:8080/ -auth admin:{{ admin_password.stdout }} install-plugin git

    - name: Install SonarQube plugin
      command: >
        java -jar /tmp/jenkins-cli.jar -s http://{{ public_ip }}:8080/ -auth admin:{{ admin_password.stdout }} install-plugin sonar:2.17.2

    - name: Install pipeline workflow-aggregator plugin
      command: >
        java -jar /tmp/jenkins-cli.jar -s http://{{ public_ip }}:8080/ -auth admin:{{ admin_password.stdout }} install-plugin workflow-aggregator:600.vb_57cdd26fdd7



